macos_option_as_alt no
#maps

map cmd+minus change_font_size only -2.0
map cmd+plus change_font_size only +2.0

#window alert

confirm_os_window_close 0

#font

font_family             GeistMono Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto

font_size               14.0

#cursor

cursor_shape            beam
cursor_color            #ea76cb
cursor_beam_thickness   1.5

#tab bar

tab_bar_edge            bottom
tab_bar_margin_width    0.0
tab_bar_margin_height   0.0 0.0
tab_bar_style           fade

#color scheme — The Dark Side

background_opacity      0.7
background              #000000
background_blur         30

foreground              #ffffff

color0                  #1a1a1a
color1                  #d20f39
color2                  #40a02b
color3                  #e5c07b
color4                  #1e66f5
color5                  #ea76cb
color6                  #7287fd
color7                  #c0caf5
color8                  #7f848e
color9                  #d20f39
color10                 #9a77cf
color11                 #e1ab32
color12                 #4d99ff
color13                 #ea76cb
color14                 #9a77cf
color15                 #ffffff

#window

hide_window_decorations titlebar-only
window_padding_width    30
remember_window_size   yes
initial_window_width   240
initial_window_height  200
window_margin_width     2

#lines
scrollback_lines        2000
