
macos_option_as_alt no
#maps

map cmd+minus change_font_size only -2.0
map cmd+plus change_font_size only +2.0

#window alert

confirm_os_window_close 0

#font

font_family             FiraCodeMono Nerd Font
bold_font               auto
italic_font             auto
bold_italic_font        auto

font_size               14.0

#cursor

cursor_shape            beam
cursor_color            white
cursor_beam_thickness   1.5

#tab bar

tab_bar_edge            bottom
tab_bar_margin_width    0.0
tab_bar_margin_height   0.0 0.0
tab_bar_style           fade

#color scheme

background_opacity      0.7
background              #000000
foreground
background_blur         30

#window

hide_window_decorations titlebar-only
window_padding_width    30
remember_window_size   yes
initial_window_width   240
initial_window_height  200
window_margin_width     2

#lines
scrollback_lines        2000