format = """
[$hostname](green) in $directory$character
"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[hostname]
ssh_only = false
format = "[$hostname](bold yellow)"

[directory]
read_only = " "
