"$schema" = "https://starship.rs/config-schema.json"

format = """
[╭─](bold #7f848e)\
[ $hostname ](bold #EA76CB)\
[  ](bold #7f848e)\
$directory\
$git_branch\
$git_status\
$nodejs$python$rust$golang$bun\
$line_break\
[╰─](bold #7f848e)\
$character"""

add_newline = false

[character]
success_symbol = '[❯](bold #40a02b)'
error_symbol = '[❯](bold #DC143C)'

[hostname]
ssh_only = false
format = '[$hostname]($style)'
style = 'bold #EA76CB'
disabled = false

[directory]
style = 'bold #7287fd'
read_only = ' 󰌾'
read_only_style = '#DC143C'
truncation_length = 3
truncate_to_repo = true
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ' '
style = 'bold #7725EE'
format = 'on [$symbol$branch]($style) '

[git_status]
style = '#e5c07b'
format = '([$all_status$ahead_behind]($style) )'
conflicted = '⚡'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '?${count}'
stashed = '✦'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[nodejs]
symbol = ' '
style = 'bold #40a02b'
format = '[$symbol($version )]($style)'

[bun]
symbol = ' '
style = 'bold #40a02b'
format = '[$symbol]($style) '

[python]
symbol = ' '
style = 'bold #e5c07b'
format = '[$symbol($version )]($style)'

[rust]
symbol = ' '
style = 'bold #EA76CB'
format = '[$symbol($version )]($style)'

[golang]
symbol = ' '
style = 'bold #7287fd'
format = '[$symbol($version )]($style)'
