#! /bin/sh


$HOME/.config/bspwm/autostart.sh


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#I II III IV V VI VII VIII IX X

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI1 -d 1 2 3 4 5
#bspc monitor HDMI2 -d 6 7 8 9 10


bspc config border_width        	1
bspc config window_gap          	10

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config single_monocle	 	true
bspc config focused_border_color 	\#FEFEFE
bspc config normal_border_color 	\#111824


bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

#open applications on specific workspaces
bspc rule -a brave desktop='^1' follow=on
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a Subl3 desktop='^2' follow=on
bspc rule -a discord desktop='^4' follow=on



bspc rule -a mpv focus=off state=floating
bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on
bspc rule -a lf locked=on sticky=on state=floating hidden=on

bspc rule -a Surf state=pseudo_tiled
bspc rule -a Dragon-drag-and-drop locked=on sticky=on 
bspc rule -a cool-retro-term state=pseudo_tiled