#!/bin/bash

# Loads all defined colors
source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
ICON_FONT="SF Pro:Semibold:14.0"
LABEL_FONT="SF Pro Display:Semibold:13.0"


sketchybar --bar height=39 \
  color=0x44000000 \
  blur_radius=30 \
  position=top \
  sticky=on \
  padding_left=10 \
  padding_right=10


sketchybar --default icon.font="$ICON_FONT" \
  icon.color=$ITEM_COLOR \
  label.font="$LABEL_FONT" \
  label.color=$ITEM_COLOR \
  background.color=$ACCENT_COLOR \
  background.corner_radius=10 \
  background.height=20 \
  padding_left=4 \
  padding_right=4 \
  icon.padding_left=6 \
  icon.padding_right=3 \
  label.padding_left=3 \
  label.padding_right=6

# -- Left Side  --
source $ITEM_DIR/spaces.sh

# -- Right Side Of Notch --
source $ITEM_DIR/media.sh

# -- Right Side --
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/memory.sh


sketchybar --update
