#!/usr/bin/env sh


#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# global settings
yabai -m config \
	mouse_follows_focus on \
	focus_follows_mouse autofocus \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist off \
	window_shadow on \
	window_animation_duration 0.0 \
	window_animation_frame_rate 120 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.5 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	split_ratio 0.60 \
	split_type auto \
	auto_balance off \
	top_padding 5 \
	bottom_padding 5 \
	left_padding 5 \
	right_padding 5 \
	window_gap 5 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:39:0

yabai -m rule --add app="^(System Settings|System Information|Activity Monitor|FaceTime|Screen Sharing|Calculator|Stickies|TinkerTool|Progressive Downloader|Transmission|Airflow|^Picture in Picture$)$" manage=off

yabai -m signal --add event=window_created action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_destroyed action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_minimized action="sketchybar -m --trigger window_change &> /dev/null"
yabai -m signal --add event=window_deminimized action="sketchybar -m --trigger window_change &> /dev/null"

yabai -m signal --add event=space_created action="sketchybar --trigger space_change"
yabai -m signal --add event=space_destroyed action="sketchybar --trigger space_change"

echo "yabai configuration loaded.."
borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=2.0
